import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import type { AnyObject, Env } from "conner.env";
// @ts-expect-error The build file generated by Workers is not ESM yet
import * as build from "../build";

const handleRequest = createPagesFunctionHandler({
  build,
  getLoadContext(context) {
    return getEnvFromContext(context);
  },
});

const getEnvFromContext = (context: EventContext<Env, "", AnyObject>): Env => {
  return context.env;
};

export const onRequest: PagesFunction = async (context) => {
  return await handleRequest(context);
};

export default onRequest;
